### ISSUE TITLE
Error in mux.js when embedding a video

### ISSUE THREAD

**Issue by Joqus** [videojs/mux.js#123]
We are embedding a video in a web page and mux.js is throwing an error. Seems like the update from 04 of October caused some issues. We are embedding the video from Wistia and mux.js shows as an error in the console.

The message is: 
Uncaught TypeError: n.default.getLevel is not a function mux.js:7 
![screen shot 2016-10-05 at 19 13 46](https://cloud.githubusercontent.com/assets/5324562/19133704/08d1d232-8b30-11e6-9f98-7fb105650ec5.png)

**Comment by ginmot** [comment]
+1

**Comment by dmlap** [comment]
Do you have an unminified stack trace of the error? Are you sure you're using this project? (We don't have a file called "minify-keys", for instance, but that's showing up in the trace)

**Comment by Joqus** [comment]
Hi @dmlap, I am embedding a video using Wistia, and mux.js is showing up in the console as an error. I believe Wistia is using mux.js in their project so I don't have control over it.
Please tell me if I can run any test that might help clarify this issue. Thanks for the help.

**Comment by dmlap** [comment]
I'd suggest reaching out to support at Wistia. It seems like the error is originating in some of their code but we won't be able to know that for sure without some details from their development team. I'm going to close this issue since we don't have enough info to do anything about it right now but feel free to continue commenting if you get more details.

**Comment by MarcosEich** [comment]
I'm sorry but I won't be able to help. It's been 8 years, I don't remember how we solved it back then and I'm not in that company anymore.
