### ISSUE TITLE
Chrome no longer requires fragments to start with a key frame

### ISSUE THREAD

**Issue by chcunningham** [videojs/mux.js#136]
The Chrome bug was fixed back in February and shipped in release version 50. 
https://bugs.chromium.org/p/chromium/issues/detail?id=229412#c77

This code can now be removed (as well as code for other containers)
https://github.com/videojs/mux.js/blob/master/lib/mp4/transmuxer.js#L319

cc: @wolenetz

**Comment by dmlap** [comment]
@chcunningham thanks for letting us know! It will be nice to drop all that complexity.

**Comment by dmlap** [comment]
@chcunningham Chrome does appear to accept media segments without starting keyframes but dropping leading non-keyframes results in video buffer gaps and a worse playback experience. More details on my testing in the referenced PR. It seems like we still want this code to ensure smooth playback for streams that don't segment on keyframes.

**Comment by wolenetz** [comment]
That's correct. MSE, not just Chrome, requires that appends following a
discontinuity detected by the MSE standard's coded frame processing
algorithm drop non-keyframes in each track until a keyframe in that track
is parsed. Otherwise, the leading nonkeyframes might be associated with an
incorrect, already buffered from a previous append, keyframe that precedes
it in decode time order.

Matt (MSE spec co-editor and Chrome MSE implementation area owner)

On Sun, Jan 1, 2017 at 11:20 AM, David LaPalomento <notifications@github.com
