### ISSUE TITLE
Should the mp4-generator support stts and other atoms?

### ISSUE THREAD

**Issue by bikegriffith** [videojs/mux.js#89]
We've diagnosed a timing problem when there are missing frames with a related library (https://github.com/dailymotion/hls.js/issues/409) and it seems that you would be vulnerable to the same problem.

Do you plan to support `stts` and other MP4 atoms that are [currently empty](https://github.com/videojs/mux.js/blob/master/lib/mp4/mp4-generator.js#L378)?

Thanks!

**Comment by imbcmdth** [comment]
We have experimental support for the edit-list atoms though it seems like all the major MSE implementations ignore them. We don't have any immediate plans to implement the `stts` atoms. I'm not sure they would help here.

The problem with the stream is missing video and audio frames. The missing video frames are already "handled" by mux.js - we pull the next frame forward in time (it starts earlier) to cover the gap.

The problem here is really the *audio* frames. The same trick of extending the sample duration does not work because the decoders process audio differently from video.

Setting the `sample_composition_time_offset` for audio samples in the `trun` actually **does** work in Firefox but not in Chrome unfortunately. It is a shame because that would be preferable to inserting silence which I think is currently the best solution.

**Comment by forbesjo** [comment]
Closing as answered

**Comment by Ivshti** [comment]
@imbcmdth where is the experimental implementation?
